### ISSUE TITLE
Move subdecks

### ISSUE THREAD

**Issue by h16nning** [h16nning/skola#56]
@eMerzh Now that we have an alternative way in place to access lower-order decks, the subdeck section could be moved. However, on smaller screen we still need some access to it. Do you have any idea where to put it?

**Comment by eMerzh** [comment]
hehe… I was thinking about that and moving cards too :) 

but I realize that if we remove them, it's important to open the current deck in sidebar while browsing decks


About how to manage that on small screen, maybe keep the current list but in a tabbed view with notebook view? 🤔 

<img width="701" alt="Capture d’écran 2024-02-13 à 12 22 58" src="https://github.com/h16nning/skola/assets/177003/161df464-57f0-4ef6-a283-bc0eaf33db9b">

it's a quick idea... maybe need to find other ways 🤔

**Comment by h16nning** [comment]
would definitely work.

I was initially thinking about something like this. Thoughts?

<img width="756" alt="image" src="https://github.com/h16nning/skola/assets/48356881/ede0b0f8-b308-4d5e-85cc-a29b310703a8">

**Comment by eMerzh** [comment]
Like dropdown/[combobox](https://mantine.dev/core/combobox/#search-input) ? Or more like some kind of "single" accordion? 

but yeah not strong feelin about this one "mine" is a bit more discoverable, but takes up more space

**Comment by h16nning** [comment]
I just build a little prototype of your version, still needs improvement, but I think it actually works quite nicely in practice

**Comment by eMerzh** [comment]
Niiiice ... 
I would remove the title below the tab and flip the tabs (putting notebook first), especially on desktop

**Comment by h16nning** [comment]
Will do that

**Comment by h16nning** [comment]
> (side note: i have (intermediate value)(...).displayPreview(...).localeCompare is not a function error 😅 )

Yes I will fix that. You probably also have cloze cards or double-sided cards in your Notebook, right? displayPreview() can return a string, which it does for normal cards, but it can also return a Promise (value needs to be fetched from sharedValue first). Obviously, localCompare as a string function doesn't exist on a Promise. I need to first create a list with sortable items without Promises that need to be resolved (like I already implemented in card_filter).

I was just too lazy to do it yesterday... 😅
