### ISSUE TITLE
Menu in Notebook view

### ISSUE THREAD

**Issue by eMerzh** [h16nning/skola#59]
Hello @h16nning  👋 
I see you are playing with combo; sorting & stuff in notebook view...

to takes from mochi :p 
i kinda like the "options" there... allthough it's  obviously "a lot" of options, maybe we don't need all that now

<img width="262" alt="Capture d’écran 2024-02-14 à 20 14 42" src="https://github.com/h16nning/skola/assets/177003/1db2df2d-fb12-4b62-85b1-a04ab451a94c">
maybe in combination with sort options?
<img width="254" alt="Capture d’écran 2024-02-14 à 20 15 06" src="https://github.com/h16nning/skola/assets/177003/da0e38da-e1f0-4af3-adf9-688e12b22fbc">

i was thinking for us, cool starting options could be:
- show all side
- show sub decks
- sort options like you did

**Comment by h16nning** [comment]
I will make show all sides and show sub decks options. Do you think they should be saved globally or deck specifically?

I don't know whether I will integrate many more sort options in the Notebook. It should be a relatively minimal place to read through your cards.

I would eventually integrate them in the card manager (which mochi doesn't have, right?). There we could have more toggable columns like Anki does:
<img width="771" alt="Bildschirmfoto 2024-02-14 um 22 26 21" src="https://github.com/h16nning/skola/assets/48356881/d4588345-7fe5-48a5-b086-77bac82f4824">

**Comment by eMerzh** [comment]
Yeah mochi doesn't have a card manager.
I'm not sure all those sort options are interesting either ... not even sure to understand the custom sort TBH :p 

Agree, we should keep it minimal 👍  
the idea i had with show all side, and sub deck is that it can reduce the noise even more ...

now, is that a deck option or global option? 🤔  good question, maybe we can start with global, keeping in mind that maybe one day it could be overridden 🤷  like keep it simple first?
Then if there's a need, we could always add more options.

(and following discussion about #61  maybe having a de-dup' option :p )

**Comment by h16nning** [comment]
### Custom Sort
I made the custom sort so you have a way to bring your cards into an order that makes sense for the content (not dependent on alphabetical order or the order of creation). I was thinking to have a option to add sections, headers and comments / annotations in between the actual cards. You could bring all of them into your personal order. As a result, you would have a type of "notebook" you could use to actually look up / reference the knowledge in your cards.

de-dup sounds useful, I was already thinking about something like that writing my answer in #61 

I agree mochi looks very clean. The issue I have with mochi is that there is so many options and different ways to do the same thing. At the same time it looks a little cluttered - if I open mochi I don't really know where to look first, if that makes sense

**Comment by h16nning** [comment]
>show all side
show sub decks
sort options like you did

Are implemented for now, can improve on it as we go along
