### ISSUE TITLE
Cloze card preview

### ISSUE THREAD

**Issue by h16nning** [h16nning/skola#64]
As mentioned in #63, the cloze card preview does look a little ugly. I think we could just remove the {{::}} stuff

**Comment by h16nning** [comment]
Affects searching and CardManagerView

**Comment by eMerzh** [comment]
i like the notebook view of the card with highlight ... ( maybe  all cloze should be highlighted ? )   but in the meantime, yeah probably remove is nicer

**Comment by eMerzh** [comment]
i think you made this better no? it looks slick now :)
