### ISSUE TITLE
React Router: Should have a queue.

### ISSUE THREAD

**Issue by h16nning** [h16nning/skola#69]
On first update, only on mobile devices (not screen-size dependent):

React Router caught the following error during render Error: Should have a queue. This is likely a bug in React. Please file an issue.

**Comment by eMerzh** [comment]
mmmh could you says more on how you reproduce this? not sure what's the issue... but i can look at this

**Comment by h16nning** [comment]
Happens as soon as you interact with the page (first click basically).

Could reproduce on:
- Chromium using the test screen sizes function in dev tools 
- actual iOS safari devices (didn't test emulated iOS safari devices with Xcode)
<img width="25" alt="Bildschirmfoto 2024-02-25 um 16 35 57" src="https://github.com/h16nning/skola/assets/48356881/4916611f-16de-458c-bcfc-c64ea04a226e">

Not reproducable on Firefox (with test screen sizes function).

I suppose it may be related to SpotlightCard (it was seeing that in the stack trace sometimes) and it started occurring around that time. However, I haven't investigated further...

**Comment by h16nning** [comment]
https://github.com/h16nning/skola/assets/48356881/c2ea5d7f-a959-4878-ac7a-dbfd37954db8

**Comment by eMerzh** [comment]
cool got it.. i'll check when i can
